### PR TITLE
Support email grouping of "effectively duplicate" exceptions

### PR DESCRIPTION
**Pull request by PeteW**
First of all let me start by saying how wonderfully effective ELMAH has been as a monitoring and operations tool in over ten years' of my career.

This PR covers an ongoing issue I've experienced in high-traffic environments. I can get thousands of error emails per day, the signal to noise ratio can be low. My goal is to group similar issues together into more consolidated messages.  In this PR I'm offering a dumb/simple behavior where **similar** exceptions are grouped together for a **retention period** where a single grouped email is sent. This is somewhat similar to issue #121 however the goal is to make the grouping functionality as basic as possible while still meeting the key goal.

**Similar** meaning exceptions of the same type and/or URL
**Retention period** meaning a group of exceptions are buffered in-memory until a max count and/or a retention time limit is exceeded.

This PR is something I'm using in my integration environments and seeing orders of magnitude less email volume, improved signal-to-noise ratio without loss of fidelity/detail.

One of the greatest qualities of ELMAH are the simplicity and compatibility. Add the module to any version of .NET framework and it just works. This PR has been faithfully written to maintain full compatibility with no side effects to any existing users. To do this, I've added a new `ErrorGroupMailModule` which inherits from `ErrorMailModule`. The changes are additive but do not affect any existing functionality. In order to enable grouping:
1. Use the `ErrorGroupMailModule` instead of `ErrorMailModule` (even though you can conceivably enable both without conflict)
2. In the `ErrorMail` configuration element enable:
  - **groupingFlushMilliseconds**: the number of milliseconds a group of errors is held in retention before flushing (sending consolidated email). If this is zero it is held indefinitely. The time of retention starts with the arrival of the first error in a group. The default is 10 minutes.
  - **groupingFlushMaxOccurrences**: the number of occurrences until a group of errors is held in retention before flushing (sending consolidated email). If this is set to zero there is no retention size limit. The default is 50
  - **groupingMethods**: the means in which exception groups are determined. Comma-separated string values. Valid values include (Url - relative or absolute path of the request without querystring) and (Exception - the type of exception thrown). Defaults to Exception

Finally, below is an example of a "consolidated" error email which you'll see prints not only the exception/url but also the count and the time range of the group:

image

### CODE REVIEW

**Comment by atifaziz** [comment]
> This PR has been faithfully written to maintain full compatibility with no side effects to any existing users. To do this, I've added a new `ErrorGroupMailModule` which inherits from `ErrorMailModule`.

Thanks for this PR, and above all, thanks for doing it in a way that's mindful towards compatibility and other users. This is a big PR touching some 17 files that will take me some time to review. Moreover, I am not actively working on ELMAH at the moment and there's no one else helping to maintain it either. I would therefore hate to see this getting neglected or stalling based on my availability. Since you've enhanced the functionality by sub-classing `ErrorMailModule`, I wonder why you wouldn't publish this as a separate package that bolts on top of ELMAH? Put another way, what are you hoping to gain (besides a much appreciated contribution) by making it an integral part of ELMAH?

**Comment by PeteW** [comment]
> what are you hoping to gain (besides a much appreciated contribution) by making it an integral part of ELMAH

I invest time into several OSS projects I personally feel have significant value. Normally I submit PRs, not fork, nor extend. What I gain in return is my desired features added to a stream of ongoing maintenance by the project caretakers.

But to your point, I do extend projects if I feel my desired features are tangential to the project's focus. As a matter of fact, if you'll look in my profile you [can see 5 years' back I wrote a rules-engine for email routing which works on top of ELMAH](https://github.com/PeteW/ElmahExtensions). Again, I feel your work in ELMAH has significant value.

Sorry to hear there's no active project maintainers at the moment. I'd be glad to volunteer my help to assist you for a few months if there is a backlog. However if you're reticent to take this on right now you can reject my PR and I'll refactor this into an extension. 

I do want to emphasize that no impact/change to existing users of ELMAH was my top priority in this PR.

**Comment by atifaziz** [comment]
> I invest time into several OSS projects I personally feel have significant value.

I commend your attitude and we need more people like you!

> Normally I submit PRs, not fork, nor extend.

Except sometimes extending is the right call.

> What I gain in return is my desired features added to a stream of ongoing maintenance by the project caretakers.

The only reason I would encourage extending here is that there isn't much maintenance going on. I am the only caretaker at the moment and while people have offered to help in the past, there's been not much follow through so all work happens on my agenda; I'm clearly the bottleneck. For me to accept anything into ELMAH at this time would mean that I alone should be willing to support it should your priorities or interests change in the near or distant future.

> I do extend projects if I feel my desired features are tangential to the project's focus. As a matter of fact, if you'll look in my profile you [can see 5 years' back I wrote a rules-engine for email routing which works on top of ELMAH](https://github.com/PeteW/ElmahExtensions).

That's awesome and nice to see you embracing the extensibility baked into ASP.NET & ELMAH. I'll be sure to point people to your extension if they come looking for the features it offers!

> Sorry to hear there's no active project maintainers at the moment. I'd be glad to volunteer my help to assist you for a few months if there is a backlog.

That's very kind of you. There's a bit of backlog in terms of getting ELMAH 2.0 out the door, which I consider to be the last version for ASP.NET. Thereafter, it seems best to start afresh given the big changes in the direction of the platform & ASP.NET itself, first the divergence with .NET Core and now the [coming convergence in .NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) (although ASP.NET's architecture will remain distinct). If you want to discuss this further, we can pick up a separate thread from this PR as it's a little off-topic.

> However if you're reticent to take this on right now you can reject my PR and I'll refactor this into an extension.

Just so that you don't feel that I am reserving any exclusive rights here, I myself have published a number of enhancements to ELMAH as pure extensions over the years, like [Eldump](https://github.com/elmah/Eldump) (a client- & server-side error log dump solution), [Bootstrapper](https://github.com/elmah/Bootstrapper) (configuration-free registration of ELMAH & more), [elvue](https://github.com/elmah/elvue) (summary reports for ELMAH error logs) and [FabMail](https://github.com/elmah/Fabmail) (error mail improved).

A quick question: If I host a repo for this as an extension under the @elmah org then would that be a fair compromise? You would wholly own and maintain the repo along with its own issues and PRs. As a separately published package, the extension would have its own release cycles and could iterate much faster than ELMAH, which is still stuck at [2.0 alpha 1](https://www.nuget.org/packages/elmah.corelibrary/2.0.0-alpha001) since 3 years! In fact, even the various `ErrorLog` implementations that used to ship as part of ELMAH have been factored out into separate repos (see #418). I'd be also happy to help you review and improve your extension. All of this wouldn't preclude merging it into the base line in the future if that's what's best.

> I do want to emphasize that no impact/change to existing users of ELMAH was my top priority in this PR.

This is a good quality PR even at a cursory glance and so I'd like to give it a fair chance and thought.

**Comment by PeteW** [comment]
@atifaziz I'll take you up on your offer. If you establish a git repo with your choice of a preferred name for this feature I'll refactor this into an extension, targeting compatibility with .NET framework 3.5+
And I'll abandon this PR. I look forward to working under your advisement on this effort.

**Comment by atifaziz** [comment]
@PeteW Splendid. How does **ErrorGroupMailer** sound? This is just the name for the repo. You're then welcome to name the assembly/package `Elmah.ErrorGroupMailer`, `Elmah.Extensions.ErrorGroupMailer` or simply `ElmahErrorGroupMailer` (dot-less).

**Comment by PeteW** [comment]
Most of the "extension" nuget packages I see follow the format of [CoreProject].[ExtensionName]. 3rd-party "extension" packages often use [CoreProject].Contrib.[ExtensionName]. 

Github repo, visual studio, nuget packages, its nice if they all share identical name.

Based on this mindset I personally prefer your first recommendation `Elmah.ErrorGroupMailer`
That being said as my years grow my opinions on project names weakens.

You create the repo and I'll establish a vs 2017 codebase with a solution name matching that of the repo.

**Comment by atifaziz** [comment]
> That being said as my years grow my opinions on project names weakens.

😄 …and [naming is hard](https://martinfowler.com/bliki/TwoHardThings.html) anyway.

**Comment by atifaziz** [comment]
@PeteW I've created [the repo][ErrorGroupMailer] and sent you an invite with full admin rights for you to do as you see fit. If you didn't get the invite or don't have the correct level of permissions then let me know. Otherwise, I look forward to you having great success with your extension. When it's ready to go 1.0, I might even swap it in on some deployments.


[ErrorGroupMailer]: https://github.com/elmah/ErrorGroupMailer

**Comment by atifaziz** [comment]
@PeteW I'm closing this assuming that work will continue on the [ErrorGroupMailer] repo.


[ErrorGroupMailer]: https://github.com/elmah/ErrorGroupMailer

**Pull request closed without merging**
